# Generated by Django 3.1.5 on 2021-01-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=240)),
                ('photo_url', models.URLField(max_length=240)),
                ('title', models.CharField(max_length=240)),
            ],
        ),
    ]
